# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sites',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
